# Project information
site_name: "Interpretador: C++ Python"
site_author: Grupo 7
site_description: >-
  Documentação do projeto de desenvolvimento de um Interpretador de C++ para Python, desenvolvido ao longo da disciplina de Compiladores 1 (2025/1) na Universidade de Brasília.

# Repository
repo_url: https://github.com/Maliz30/Interpretador_Cpp-Py#
repo_name: Interpretador_Cpp-Py

# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
        primary: deep purple
        accent: purple

extra_css: [stylesheets/extra.css]

# Page tree
nav: 
  - Início: index.md
  - Documentação de Sprints: 
    - Planejamento das sprints: sprints/planejamento.md
    - Template: sprints/template.md
  - Ponto de Controle 1: ponto-controle-1/index.md
  # - Ponto de Controle 2: ponto-controle-2/index.md
  # - Entrega Final: entrega-final/index.md
    # - Estrutura do projeto:
    # - Decisões técnicas:
    # - Problemas encontrados e soluções adotadas:
