# Project information
site_name: "Interpretador: C++"
site_author: Grupo 7
site_description: >-
  Documentação do projeto de desenvolvimento de um Interpretador de C++ para Python, desenvolvido ao longo da disciplina de Compiladores 1 (2025/1) na Universidade de Brasília.

# Repository
repo_url: https://github.com/Maliz30/Interpretador_Cpp
repo_name: Interpretador_Cpp

# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
        primary: deep purple
        accent: purple

extra_css: [stylesheets/extra.css]

# Page tree
nav: 
  - Início: 
    - Sobre: index.md
    - Como rodar: como-rodar.md
  - O Interpretador:
    - Como configurar o ambiente: interpretador/como-config.md
    - Subconjunto de C++ a ser suportado: interpretador/subconjunto.md
  - Organização e Planejamento:
    - Planejamento das sprints: organizacao-planejamento/planejamento.md
    - Boas Práticas: organizacao-planejamento/boas-praticas.md
  - Documentação de Sprints: 
    - Sprint 1:
      - Planning: sprints/sprint-1/sprint-planning.md
      - Review: sprints/sprint-1/sprint-review.md
    - Sprint 2:
      - Planning: sprints/sprint-2/sprint-planning.md
      - Review: sprints/sprint-2/sprint-review.md
    - Sprint 3:
      - Planning: sprints/sprint-3/sprint-planning.md
      - Review: sprints/sprint-3/sprint-review.md
    - Sprint 4:
      - Planning: sprints/sprint-4/sprint-planning.md
      - Review: sprints/sprint-4/sprint-review.md  
    - Sprint 5:
      - Planning: sprints/sprint-5/sprint-planning.md
      - Review: sprints/sprint-5/sprint-review.md 
    - Sprint 6:
      - Planning: sprints/sprint-6/sprint-planning.md
      - Review: sprints/sprint-6/sprint-review.md      
  - Ponto de Controle 1: ponto-controle-1/index.md     
  - Ponto de Controle 2: ponto-controle-2/index.md
  - Entrega Final:
    - Entrega Final: entrega-final/index.md
    - Estrutura do projeto: entrega-final/estrutura-projeto.md
    - Decisões técnicas: entrega-final/decisoes-tomadas.md
    - Problemas encontrados e soluções adotadas: entrega-final/problemas-encontrados-solucao.md